# Generated by Django 5.2.3 on 2026-04-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='important',
        ),
    ]
