# Generated by Django 5.2.3 on 2026-04-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
